"""Public OpenRBus package facade."""

from .access import (
    AsyncBulkObjectAccess,
    AsyncNodeAuthorizationAccess,
    AsyncObjectAccess,
    ObjectRead,
    RawReadResult,
)
from .access_policy import AccessPolicy
from .authorization import (
    CanIpGatewayAuthorizer,
    GatewayAuthorizationResult,
    NodeAuthorizationResult,
    NodeAuthorizer,
    TeaKeyComponent,
    compute_authentication_response,
)
from .client import OpenRBusClient, ReadFailure, ReadOutcome, ReadResult, SessionAccess, WritePlan
from .discovery import (
    CapabilityReference,
    DeviceIdentity,
    assigned_nodes,
    discover_capabilities,
    discover_devices,
    identify_node,
)
from .errors import (
    AccessLevelAmbiguityError,
    AccessLevelError,
    AccessLevelUnavailableError,
    AccessPolicyError,
    AuthenticationError,
    AuthorizationKeyError,
    AuthorizationUnsupportedError,
    CanOpenAbortError,
    ChecksumError,
    ConnectionFailedError,
    InsufficientAccessLevelError,
    NodeAuthorizationError,
    OpenRBusError,
    ProtocolError,
    RegistryError,
    RequestTimeoutError,
    SegmentationError,
    TransportError,
    UnknownRegisterError,
    UnsafeWriteError,
    ValidationError,
    WritesDisabledError,
    WriteVerificationError,
)
from .object_client import RawObjectClient
from .protocol import ObjectAddress
from .registry import (
    AccessLevel,
    AccessOperation,
    AccessRequirement,
    RegisterDefinition,
    Registry,
    WireType,
    WriteSafety,
)
from .value_codec import CanOpenTimeOfDay, StructuredValue

__all__ = [
    "AccessLevel",
    "AccessLevelAmbiguityError",
    "AccessLevelError",
    "AccessLevelUnavailableError",
    "AccessOperation",
    "AccessPolicy",
    "AccessPolicyError",
    "AccessRequirement",
    "AsyncBulkObjectAccess",
    "AsyncNodeAuthorizationAccess",
    "AsyncObjectAccess",
    "AuthenticationError",
    "AuthorizationKeyError",
    "AuthorizationUnsupportedError",
    "CanIpGatewayAuthorizer",
    "CanOpenAbortError",
    "CanOpenTimeOfDay",
    "CapabilityReference",
    "ChecksumError",
    "ConnectionFailedError",
    "DeviceIdentity",
    "GatewayAuthorizationResult",
    "InsufficientAccessLevelError",
    "NodeAuthorizationError",
    "NodeAuthorizationResult",
    "NodeAuthorizer",
    "ObjectAddress",
    "ObjectRead",
    "OpenRBusClient",
    "OpenRBusError",
    "ProtocolError",
    "RawObjectClient",
    "RawReadResult",
    "ReadFailure",
    "ReadOutcome",
    "ReadResult",
    "RegisterDefinition",
    "Registry",
    "RegistryError",
    "RequestTimeoutError",
    "SegmentationError",
    "SessionAccess",
    "StructuredValue",
    "TeaKeyComponent",
    "TransportError",
    "UnknownRegisterError",
    "UnsafeWriteError",
    "ValidationError",
    "WireType",
    "WritePlan",
    "WriteSafety",
    "WriteVerificationError",
    "WritesDisabledError",
    "assigned_nodes",
    "compute_authentication_response",
    "discover_capabilities",
    "discover_devices",
    "identify_node",
]
